apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus-netmon
    jsonData:
      httpMethod: GET
      queryTimeout: 60s
      timeInterval: 15s
