apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netmon-agent
  namespace: monitoring
  labels:
    app: netmon-agent
    component: agent
spec:
  selector:
    matchLabels:
      app: netmon-agent
  template:
    metadata:
      labels:
        app: netmon-agent
        component: agent
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: netmon-agent
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: agent
        image: zhoushoujian/go-net-monitoring:latest
        imagePullPolicy: Always
        env:
        - name: COMPONENT
          value: "agent"
        - name: NETWORK_INTERFACE
          value: "eth0"  # 根据实际情况调整
        - name: SERVER_URL
          value: "http://netmon-server.monitoring.svc.cluster.local:8080/api/v1/metrics"
        - name: REPORT_INTERVAL
          value: "10s"
        - name: LOG_LEVEL
          value: "info"
        - name: BUFFER_SIZE
          value: "1000"
        - name: IGNORE_LOCALHOST
          value: "true"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: logs
          mountPath: /app/logs
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "pgrep agent > /dev/null"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "pgrep agent > /dev/null"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: logs
        hostPath:
          path: /var/log/netmon-agent
          type: DirectoryOrCreate
      restartPolicy: Always

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netmon-agent
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netmon-agent
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netmon-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netmon-agent
subjects:
- kind: ServiceAccount
  name: netmon-agent
  namespace: monitoring
