apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netmon-config
  namespace: monitoring
data:
  agent.yaml: |
    server:
      host: "netmon-server.monitoring.svc.cluster.local"
      port: 8080

    monitor:
      interface: "eth0"
      protocols:
        - "tcp"
        - "udp"
        - "http"
        - "https"
        - "dns"
      report_interval: "10s"
      buffer_size: 1000
      filters:
        ignore_localhost: true
        ignore_ports:
          - 22    # SSH
          - 123   # NTP
        ignore_ips:
          - "127.0.0.1"
          - "::1"

    reporter:
      server_url: "http://netmon-server.monitoring.svc.cluster.local:8080/api/v1/metrics"
      timeout: "10s"
      retry_count: 3
      batch_size: 100

    log:
      level: "info"
      format: "json"
      output: "stdout"

  server.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080

    storage:
      type: "memory"
      retention: "24h"

    log:
      level: "info"
      format: "json"
      output: "stdout"
