global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'go-net-monitoring'
    static_configs:
      - targets: ['server:8080']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http
