global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 网络监控Server
  - job_name: 'network-monitoring'
    static_configs:
      - targets: ['network-server:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # 如果有多个Server实例
  # - job_name: 'network-monitoring-cluster'
  #   static_configs:
  #     - targets: 
  #       - 'network-server-1:8080'
  #       - 'network-server-2:8080'
  #       - 'network-server-3:8080'

# 告警规则配置
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093
