# Agent配置文件 - macOS版本
server:
  host: "localhost"                # 连接到本地Server或远程Server
  port: 8080

monitor:
  interface: "en0"                 # macOS常用网络接口 (en0为主网卡)
  protocols:
    - "tcp"
    - "udp"
    - "http"
    - "https"
    - "dns"
  report_interval: "10s"           # 上报间隔
  buffer_size: 1000                # 缓冲区大小
  filters:
    ignore_localhost: true         # 忽略本地回环流量
    ignore_ports:
      - 22    # SSH
      - 123   # NTP
      - 5353  # mDNS (macOS Bonjour)
    ignore_ips:
      - "127.0.0.1"
      - "::1"
      - "169.254.0.0/16"          # Link-local addresses
      - "224.0.0.0/4"             # Multicast addresses

reporter:
  server_url: "http://localhost:8080/api/v1/metrics"
  timeout: "10s"
  retry_count: 3
  batch_size: 100
  
  # 混合方案配置
  mode: "incremental"              # 增量模式上报
  include_totals: true             # 同时包含累计数据
  agent_id: "${HOSTNAME}"          # Agent唯一标识，支持环境变量

log:
  level: "info"                    # debug, info, warn, error
  format: "text"                   # macOS开发时使用text格式更易读
  output: "stdout"                 # stdout, stderr, 或文件路径

# macOS特定配置
macos:
  # 网络接口检测
  auto_detect_interface: true      # 自动检测主网络接口
  preferred_interfaces:            # 优先使用的接口列表
    - "en0"                       # 主以太网/WiFi
    - "en1"                       # 备用网络接口
    - "utun0"                     # VPN接口
  
  # 权限相关
  require_sudo: true               # 明确标识需要sudo权限
  
  # 性能优化
  use_bpf: true                   # 使用BPF进行高效包捕获
  capture_timeout: "1s"           # 包捕获超时时间
