# Agent配置文件 - 纯增量方案(Server端累计)
server:
  host: "host.docker.internal"     # 使用特殊的Docker DNS名称访问宿主机
  port: 8080

# Agent信息配置
agent:
  id: ""                           # Agent唯一标识，为空时自动生成
  name: "go-net-monitoring-agent"  # Agent名称
  version: "2.0.0-ebpf"           # Agent版本
  tags:                           # Agent标签
    - "production"
    - "linux"
  report_online: true             # 是否上报上线信息
  online_report_url: "http://host.docker.internal:8080/api/v1/agent/online"  # 上线信息上报URL
  heartbeat_interval: "60s"       # 心跳间隔
  auto_detect_interface: true     # 是否自动检测网卡

monitor:
  interface: "eth0"                # 网络接口，Docker中通常是eth0，本地可能是en0/wlan0等
  protocols:
    - "tcp"
    - "udp"
    - "http"
    - "https"
    - "dns"
  report_interval: "10s"           # 上报间隔
  buffer_size: 1000                # 缓冲区大小
  filters:
    ignore_localhost: true
    ignore_ports:
      - 22    # SSH
      - 123   # NTP
    ignore_ips:
      - "127.0.0.1"
      - "::1"
    ignore_domains:
      - "q.us-east-1.amazonaws.com"
      - "client-telemetry.us-east-1.amazonaws.com"
      - "*.amazonaws.com"
    only_domains: []               # 如果指定，只监控这些域名

# 持久化配置 - 解决Agent重启数据丢失问题
persistence:
  enabled: true                    # 启用持久化
  state_file: "/var/lib/netmon/agent-state.json"  # 状态文件路径
  save_interval: "30s"             # 保存间隔
  backup_count: 3                  # 备份文件数量

# eBPF程序配置
ebpf:
  program_path: "release/linux-amd64/bpf/xdp_monitor.o"  # 默认使用相对路径
  fallback_paths:                  # 备用路径列表，按优先级排序
    - "release/linux-amd64/bpf/xdp_monitor_linux.o"  # 兼容版本
    - "/opt/go-net-monitoring/bpf/xdp_monitor.o"     # 系统安装路径
    - "/usr/local/bin/bpf/xdp_monitor.o"             # 传统路径
  enable_fallback: true            # 启用模拟模式回退

reporter:
  server_url: "http://localhost:8080/api/v1/metrics"  # 使用特殊的Docker DNS名称访问宿主机
  timeout: "10s"
  retry_count: 3
  retry_delay: "5s"
  batch_size: 100
  enable_tls: false
  tls_cert_path: ""
  tls_key_path: ""
  
  # 增量上报配置
  mode: "incremental"              # 固定为增量模式
  agent_id: "${HOSTNAME}"          # Agent唯一标识，支持环境变量

log:
  level: "debug"                   # debug, info, warn, error
  format: "json"                   # json, text
  output: "stdout"                 # stdout, stderr, 或文件路径
