# Agent配置文件 - 支持混合方案(Agent持久化 + Server智能累计)
server:
  host: "localhost"                # Docker host网络模式下使用localhost，容器网络使用server
  port: 8080

monitor:
  interface: "eth0"                # 网络接口，Docker中通常是eth0，本地可能是en0/wlan0等
  protocols:
    - "tcp"
    - "udp"
    - "http"
    - "https"
    - "dns"
  report_interval: "10s"           # 上报间隔
  buffer_size: 1000                # 缓冲区大小
  filters:
    ignore_localhost: true
    ignore_ports:
      - 22    # SSH
      - 123   # NTP
    ignore_ips:
      - "127.0.0.1"
      - "::1"
    ignore_domains:
      - "q.us-east-1.amazonaws.com"
      - "client-telemetry.us-east-1.amazonaws.com"
      - "*.amazonaws.com"
    only_domains: []               # 如果指定，只监控这些域名

# 持久化配置 - 解决Agent重启数据丢失问题
persistence:
  enabled: true                    # 启用持久化
  state_file: "/var/lib/netmon/agent-state.json"  # 状态文件路径
  save_interval: "30s"             # 保存间隔
  backup_count: 3                  # 备份文件数量

# eBPF程序配置
ebpf:
  program_path: "/opt/go-net-monitoring/bpf/xdp_monitor.o"  # 生产环境路径
  # program_path: "bpf/xdp_monitor.o"  # 开发环境相对路径
  fallback_paths:                  # 备用路径列表，按优先级排序
    - "bpf/xdp_monitor.o"
    - "bin/bpf/xdp_monitor.o"
    - "bin/bpf/xdp_monitor_linux.o"
    - "/usr/local/bin/bpf/xdp_monitor.o"
  enable_fallback: true            # 启用模拟模式回退

reporter:
  server_url: "http://localhost:8080/api/v1/metrics"  # Server API地址
  timeout: "10s"
  retry_count: 3
  retry_delay: "5s"
  batch_size: 100
  enable_tls: false
  tls_cert_path: ""
  tls_key_path: ""
  
  # 混合方案配置
  mode: "incremental"              # 增量模式上报
  include_totals: true             # 同时包含累计数据
  agent_id: "${HOSTNAME}"          # Agent唯一标识，支持环境变量

log:
  level: "info"                    # debug, info, warn, error
  format: "json"                   # json, text
  output: "stdout"                 # stdout, stderr, 或文件路径
