# Agent配置文件
server:
  host: "localhost"    # host网络模式下使用localhost
  port: 8080

monitor:
  interface: "eth0"  # Docker容器中通常使用eth0
  protocols:
    - "tcp"
    - "udp"
    - "http"
    - "https"
    - "dns"
  report_interval: "10s"
  buffer_size: 1000
  filters:
    ignore_localhost: true
    ignore_ports:
      - 22    # SSH
      - 123   # NTP
    ignore_ips:
      - "127.0.0.1"
      - "::1"
      # 移除了本机IP过滤，这样出站流量才能被统计
    only_domains: []  # 如果指定，只监控这些域名

reporter:
  server_url: "http://localhost:8080/api/v1/metrics"  # host网络模式下使用localhost
  timeout: "10s"
  retry_count: 3
  retry_delay: "5s"
  batch_size: 100
  enable_tls: false
  tls_cert_path: ""
  tls_key_path: ""

log:
  level: "info"      # debug, info, warn, error
  format: "json"     # json, text
  output: "stdout"   # stdout, stderr, 或文件路径
