# Server配置文件 - Redis存储版本
http:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  enable_tls: false
  tls_cert_path: ""
  tls_key_path: ""

metrics:
  path: "/metrics"
  enabled: true
  interval: "15s"

storage:
  type: "redis"       # 使用Redis存储
  ttl: "0s"          # 不设置过期时间，由Prometheus管理数据保留
  max_entries: 0      # Redis存储不需要限制条目数
  
  # Redis配置
  redis:
    host: "localhost"
    port: 6379
    password: ""      # Redis密码，如果有的话
    db: 0            # Redis数据库编号
    pool_size: 10    # 连接池大小
    timeout: "5s"    # 连接超时时间

log:
  level: "info"      # debug, info, warn, error
  format: "json"     # json, text
  output: "stdout"   # stdout, stderr, 或文件路径
